source 'https://rubygems.org'

# Mongoid for mongodb integration
gem 'mongoid'
gem 'bson_ext'

gem 'rails', '4.2.4'

gem 'rails-api'

gem 'spring', :group => :development




# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
